### ISSUE TITLE
머

### ISSUE THREAD

**Issue by ghghgh223** [storycraft/osu-player#2]
* os 버젼 : Windows 10 Home insider preview 평가본입니다. Build 17025.rs_prerelease. 171020-1626
* 실행중이던 프로그램 : 크롬(나무위키 2탭, 구글 드라이브), 디스코드, 파일 관리자, 카카오톡

버그 목록

파일을 실행하면 바탕화면으로 적용되는것이 아니라 다른 모든것들을 무시하고 가장 우선순위로 개별적인 창(?)으로 실행됨. 이 상태에선 alt + tap이나 win + tap이 작동하지 않고 작업 관리자를 실행시켜도 바로 Osu wallpaper로 강제전환? 됨

노래가 한곡 끝나면 다음 노래는 나오지만 배경등은 멈춰서 넘어가질 않음. 단 2회차 실행시에는 잘 넘어갔음.

제목 텍스트가 규격을 벗어남. 머 개발자가 알아서 고치겠지

일해라 스땅

**Comment by storycraft** [comment]
**제목 텍스트 문제는 정식 릴리즈가 아니니, 바로 고치지 않을 것.**

창이 맨 위로 뜬다는 것은 해당 창이 `WorkerW` 창으로 제대로 인젝팅이 안되고 최 상위 핸들에 인젝팅 된 것 으로 보임.

배경 등이 멈춰서 넘어가지 않는 것은 disk io 오류 인 것으로 보이며, 버그로 추가.


> 아직 프리 릴리즈 버젼이기 때문에 다른 버그가 있을 수도 있습니다.
